#!/bin/bash

containsElement () {
  local e
  for e in "${PORTS[@]}"
  do
    if [ "$e" == "$1" ]
    then
      contains=1
      return
    fi
  done
  contains=0
}

usage () {
  echo "usage: $0 [min] [max]"
}

if [[ "$1" == "-h" || "$1" == "--help" ]]; then
  usage
  exit 0
fi

if [ -n "$1" ]; then
  if [[ $1 != [0-9]* ]]; then
    usage
    exit 1
  else
    MIN=$1
  fi
else
  MIN=1023
fi

if [ -n "$2" ]; then
  if [[ $2 != [0-9]* ]]; then
    usage
    exit 1
  else
    MAX=$2
  fi
else
  MAX=65535
fi

if [[ $MAX -lt $MIN || $MIN -lt 0 || $MAX -gt 65535 ]]; then
  usage
  exit 1
fi

PORTS=($(netstat -ta | tail -n +3 | awk {'print $4'} | cut -d : -f2))

current=$MIN

while [ $current -lt $MAX ]
do
  containsElement $current

  if [ $contains -eq 0 ];
  then
    echo $current
    exit 0
  fi

  current=$(expr $current + 1)
done

exit 1

